/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package farm;


interface Talker {
    String talk();
}


abstract class Animal implements Talker {
    protected String name;

    public Animal(String name) {
        this.name = name;
    }

    public abstract String talk();
}

/// NOSSA EQUIPE

class Radio implements Talker {
     @Override
    public String talk() {
        return " ***toca música*** ";
    }   
}

class Parrot extends Animal {

    public Parrot(String name) {
        super(name);
    }

    @Override
    public String talk() {
        return this.name +" diz croc.";
    }

}

class Cat extends Animal {

    public Cat(String name) {
        super(name);
    }

    @Override
    public String talk() {
        return this.name +" diz miau.";
    }
}

class Dog extends Animal {

    public Dog(String name) {
        super(name);
    }

    @Override
    public String talk() {
        return this.name +" diz au au.";
    }
}

///

public class App {
    public static void main(String[] args) {
        System.out.println("Farm!");
        Talker farm[] = { 
            new Cat("Felix"), 
            new Cat("Jefferson"), 
            new Dog("Bilu"),
            new Parrot("Loro"),
            new Radio()
        };
        for (Talker a : farm) {
            System.out.println(a.talk());
        }
    }
}
